[versions]
android-targetSdk = "36"
android-compileSdk = "36"
android-minSdk = "26"
android-patchVersion = "0"
android-minorVersion = "11"
android-majorVersion = "1"

aboutlibraries = "12.2.4"
androidGradlePlugin = "8.13.2"
androidx-activity = "1.12.2"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.6"
baselineprofile = "1.4.1"
billing = "8.0.0"
buildkonfig = "0.17.1"
composerules = "0.0.26"
compose-navigation = "2.9.1"
compose-multiplatform = "1.9.0"
compose-runtime = "1.10.0"
composeIcons = "1.1.1"
datastorePreferencesCore = "1.1.7"
detekt = "1.23.8"
espressoCore = "3.7.0"
firebase-bom = "34.4.0"
firebase-crashlytics-plugin = "3.0.6"
firebase-perf-plugin = "2.0.2"
google-services = "4.4.4"
haze = "1.7.1"
junit = "4.13.2"
junitVersion = "1.3.0"
koin = "4.1.1"
kotlin = "2.2.20"
kotlinx-immutable = "0.4.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktlint = "0.50.0"
material3WindowSizeClass = "1.9.0"
mpfilepicker = "3.1.0"
nativeDriver = "2.1.0"
org-jetbrains-kotlin-jvm = "2.2.20"
profileinstaller = "1.4.1"
purchases-kmp = "2.2.14+17.24.0"
splashcreen = "1.0.1"
sqlDelight = "2.1.0"
stately = "2.1.0"
uiautomator = "2.3.0"
jetbrains-kotlinxDatetime = "0.6.2"
uitoolingandroid = "1.10.0"

[libraries]
aboutlibraries_compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidx-activity = { module = "androidx.activity:activity", version = "androidx-activity" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uitoolingandroid" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "baselineprofile" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferencesCore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
build-konfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }
compose-compiler-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-multiplatform" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
composeIcons-tablerIcons = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "composeIcons" }
composerules = { module = "com.twitter.compose.rules:detekt", version.ref = "composerules" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "jetbrains-kotlinxDatetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
material3-windowSizeClass = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
mpfilepicker = { module = "com.darkrockstudios:mpfilepicker", version.ref = "mpfilepicker" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "nativeDriver" }
revenuecat-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "purchases-kmp" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashcreen" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
stately = { module = "co.touchlab:stately-common", version.ref = "stately" }

[plugins]
deeplinkLauncher-composeMultiplatform = { id = "dev.koga.deeplinklauncher.compose-multiplatform" }
deeplinkLauncher-multiplatform = { id = "dev.koga.deeplinklauncher.multiplatform" }
deeplinkLauncher-codeAnalysis = { id = "dev.koga.deeplinklauncher.code-analysis" }

aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineProfile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
build-konfig = { id = "com.codingfeline.buildkonfig" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
firebasePerf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf-plugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
